## 💻Setup

NumPy (atau Numerical Python) adalah pustaka Python yang memungkinkan kita melakukan operasi numerik pada array angka dengan Python. Modul aljabar linear NumPy, linalg, memungkinkan kita melakukan operasi pada matriks. Fungsi matrix_rank dalam modul ini menghitung rank dari sebuah matriks. Jalankan sel berikut untuk melihat demonstrasi cara kerjanya:


## 📚 Rank of a Matrix

**Rank** dari sebuah matriks adalah jumlah maksimum baris atau kolom yang saling independen secara linear.  
Artinya, rank ngasih tau seberapa banyak informasi unik yang ada di dalam matriks itu.

- Rank tinggi = matriks lebih "penuh" informasi.
- Rank rendah = matriks banyak redundansi / bisa dikompres.

**Contoh:**
- Matriks 3x3 dengan rank 3 → semua baris/kolom unik.
- Matriks 3x3 dengan rank 1 → semua baris/kolom saling kelipatan.

Rank ini penting banget, apalagi buat LoRA/QLoRA, karena teknik itu ngegunain **low-rank approximations** buat ngehemat memori dan komputasi.



In [1]:
import numpy as np
A = np.array([[1, 3, 2],
              [4, 0, 8],
              [5, 7, 10]])
print("Rank of A:") 
print(np.linalg.matrix_rank(A))

Rank of A:
2


## Soal Rank of a matrix
Hitung rank (pangkat) dari matriks B dan C di bawah ini, terus simpen hasilnya ke dalam variabel rank_B dan rank_C. Setelah itu, print hasilnya biar bisa dibandingin sama nilai yang seharusnya di diagram di atas.

In [13]:
B = [[3,1,0],
    [15,5,0],
    [12,4,0]]

C = [[5,3,1],
    [1,5,9],
    [4,3,2]]

### YOUR SOLUTION HERE ###

print("Rank of B:") 
rank_B = np.linalg.matrix_rank(B)
print(rank_B)
print("Rank of C:") 
rank_C = np.linalg.matrix_rank(C)
print(rank_C)
#print(rank_B, rank_C)

Rank of B:
1
Rank of C:
2


## Matrix decomposition 

Sekarang kita bakal ngecek contoh matrix decomposition alias dekomposisi matriks. Di bawah ini ada tiga matriks: W, P, dan Q, yang semuanya punya rank 2.

NumPy punya fitur keren buat ngali matriks pake simbol @. Contohnya, perkalian matriks B dan C di checkpoint sebelumnya ditulis kayak gini: B@C. Nah, kita bakal ngecek apakah P dan Q itu emang beneran hasil dekomposisi dari matriks W.

Langkah-langkahnya:

Bikin matriks S, hasil dari P dikali Q.

Terus bikin matriks baru, difference_matrix, yaitu S dikurangin W.

Print dua-duanya biar bisa dicek apakah S sama kayak W atau nggak.

In [6]:
print(A@B)

[[ 72  24   0]
 [108  36   0]
 [240  80   0]]


In [12]:
W = np.array([[ 5,  6, -3,  8,  9],
       [ 0,  0,  0,  0,  0],
       [ 2,  2, -1,  3,  3],
       [-5,  0,  0, -5,  0],
       [ 0,  4, -2,  2,  6]])



P = np.array([[3,1],
              [0,0],
              [1,0],
              [0,5],
              [2,4]])

Q = np.array([[2,2,-1,3,3],
              [-1,0,0,-1,0]])


print("Rank of W:", np.linalg.matrix_rank(W))
print("Rank of P:", np.linalg.matrix_rank(P))
print("Rank of Q:", np.linalg.matrix_rank(Q))

### YOUR SOLUTION HERE ##
S = P@Q
difference_matrix = W - S
print(S)
print(difference_matrix)

#print(S)
#print(difference_matrix)

Rank of W: 2
Rank of P: 2
Rank of Q: 2
[[ 5  6 -3  8  9]
 [ 0  0  0  0  0]
 [ 2  2 -1  3  3]
 [-5  0  0 -5  0]
 [ 0  4 -2  2  6]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


## Pengurangan Parameter

Misalnya nih ya, anggap aja matriks W dari checkpoint sebelumnya itu adalah weight matrix (matriks bobot) di sebuah LLM (Large Language Model). (Emang agak ngaco sih anggapannya, soalnya LLM beneran tuh punya matriks gede banget sampe jutaan atau miliaran elemen – tapi kita ikutin aja skenarionya bentar 😂)

Inget ya, jumlah parameter yang dilatih di neural network itu sama kayak jumlah elemen yang ada di weight matrix-nya. Nah buat ngecek itu, kita tinggal print bentuk (shape) dari matriks W, dan juga matriks hasil dekomposisinya, yaitu P dan Q.

In [8]:
print (W.shape, P.shape, Q.shape)

(5, 5) (5, 2) (2, 5)


Jumlah parameter di matriks W itu:

$$W_{\text{params}} = 5*5 = 25$$

Setelah didekomposisi, jumlah parameternya berubah jadi gabungan dari jumlah elemen di matriks P dan Q. Nah, sekarang hitung totalnya dan simpen hasilnya ke dalam variabel total_params_after_lora.

In [ ]:
total_params_after_lora = P.shape[0] * P.shape[1] + Q.shape[0] * Q.shape[1]
print("Total parameters after LoRA:", total_params_after_lora)

Total parameters after LoRA: 20


: 